/* Generated by BIN2S - please don't edit directly */
#pragma once
#include <stddef.h>
#include <stdint.h>

extern const uint8_t main_dol[];
extern const uint8_t main_dol_end[];
#if __cplusplus >= 201103L
static constexpr size_t main_dol_size=4008832;
#else
static const size_t main_dol_size=4008832;
#endif
